FROM docker.io/library/python:3.9.12-slim-buster

LABEL purpose="hippocampus-base"

COPY ./requirements.txt requirements.txt

RUN apt-get update \
    && apt-get install -y wget curl ffmpeg vim procps\
    && /usr/local/bin/python -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && rm -rf ~/.cache/pip
