# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfdlserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10tfdlserver.proto\x12\ntfdlserver")\n\nTensorData\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02"R\n\x0e\x46orwardRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12%\n\x05input\x18\x03 \x03(\x0b\x32\x16.tfdlserver.TensorData"T\n\x0f\x46orwardResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12&\n\x06output\x18\x04 \x03(\x0b\x32\x16.tfdlserver.TensorData2R\n\nTFDLServer\x12\x44\n\x07\x66orward\x12\x1a.tfdlserver.ForwardRequest\x1a\x1b.tfdlserver.ForwardResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tfdlserver_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _TENSORDATA._serialized_start = 32
    _TENSORDATA._serialized_end = 73
    _FORWARDREQUEST._serialized_start = 75
    _FORWARDREQUEST._serialized_end = 157
    _FORWARDRESPONSE._serialized_start = 159
    _FORWARDRESPONSE._serialized_end = 243
    _TFDLSERVER._serialized_start = 245
    _TFDLSERVER._serialized_end = 327
# @@protoc_insertion_point(module_scope)
