# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tfdlserver_pb2 as tfdlserver__pb2


class TFDLServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.forward = channel.unary_unary(
            "/tfdlserver.TFDLServer/forward",
            request_serializer=tfdlserver__pb2.ForwardRequest.SerializeToString,
            response_deserializer=tfdlserver__pb2.ForwardResponse.FromString,
        )


class TFDLServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def forward(self, request, context):
        """Sends a network forward request"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TFDLServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "forward": grpc.unary_unary_rpc_method_handler(
            servicer.forward,
            request_deserializer=tfdlserver__pb2.ForwardRequest.FromString,
            response_serializer=tfdlserver__pb2.ForwardResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tfdlserver.TFDLServer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TFDLServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def forward(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfdlserver.TFDLServer/forward",
            tfdlserver__pb2.ForwardRequest.SerializeToString,
            tfdlserver__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
